### ISSUE TITLE
Publish on F-Droid

### ISSUE THREAD

**Issue by CarlSchwan** [agateau/burgerparty#1]
It would be cool if burger party is release in the F-Droid store.

**Comment by agateau** [comment]
Yes, I need to look into how to do this!

**Comment by TheLastProject** [comment]
Someone on the F-Droid forum asked about this game: https://forum.f-droid.org/t/could-we-get-this-game-app-in-f-droid/12396

Cool to see you approve.

Just curious, is building this game similar to building Pixel Wheels? If so I could give this a shot perhaps, just wondering if I should take the current Pixel Wheels build script as base or not.

**Comment by agateau** [comment]
> Just curious, is building this game similar to building Pixel Wheels?

No, it's very different, and probably simpler. Pixel Wheels build system has to generate assets. Burger Party repository contains the generated assets so you don't have to worry about that.

The "only" issue is the game is old, it was developed using Eclipse (Android Studio was not a thing back then!), so its build system does not use Gradle. I have no idea if this build is easy to automate in F-Droid.

**Comment by shuvashish76** [comment]
Thanks for this game.
Live on F-Droid : https://www.f-droid.org/en/packages/com.agateau.burgerparty/

**Comment by licaon-kter** [comment]
@agateau 
`2023-11-05 00:36:39,896 ERROR: Could not build app com.agateau.burgerparty: Downloading Binaries from https://github.com/agateau/burgerparty/releases/download/1.4.3/burgerparty-1.4.3-agc.apk failed.`

as there's no APK here? https://github.com/agateau/burgerparty/releases/tag/1.4.3

**Comment by agateau** [comment]
> @agateau `2023-11-05 00:36:39,896 ERROR: Could not build app com.agateau.burgerparty: Downloading Binaries from https://github.com/agateau/burgerparty/releases/download/1.4.3/burgerparty-1.4.3-agc.apk failed.`
> 
> as there's no APK here? https://github.com/agateau/burgerparty/releases/tag/1.4.3

Oups, this is fixed now!
